# Generated by Django 3.1.7 on 2021-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210423_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='discountprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
