# Generated by Django 3.1.7 on 2021-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_fooditems_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='discountprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
